### ISSUE TITLE
Could not pass event PlayerJoinEvent to sTablist v3.0.0-pre4

### ISSUE THREAD

**Issue by TwanLuttik** [DevJul1an/sTablist#2]
i got this error when a player joined:

ERROR:
[06:22:59 ERROR]: Could not pass event PlayerJoinEvent to sTablist v3.0.0-pre4
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[server.jar:git-Spigot-549c1fa-70cc382]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[server.jar:git-Spigot-549c1fa-70cc382]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [server.jar:git-Spigot-549c1fa-70cc382]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [server.jar:git-Spigot-549c1fa-70cc382]
        at net.minecraft.server.v1_12_R1.PlayerList.onPlayerJoin(PlayerList.java:346) [server.jar:git-Spigot-549c1fa-70cc382]
        at net.minecraft.server.v1_12_R1.PlayerList.a(PlayerList.java:166) [server.jar:git-Spigot-549c1fa-70cc382]
        at net.minecraft.server.v1_12_R1.LoginListener.b(LoginListener.java:159) [server.jar:git-Spigot-549c1fa-70cc382]
        at net.minecraft.server.v1_12_R1.LoginListener.e(LoginListener.java:57) [server.jar:git-Spigot-549c1fa-70cc382]
        at net.minecraft.server.v1_12_R1.NetworkManager.a(NetworkManager.java:233) [server.jar:git-Spigot-549c1fa-70cc382]
        at net.minecraft.server.v1_12_R1.ServerConnection.c(ServerConnection.java:140) [server.jar:git-Spigot-549c1fa-70cc382]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:845) [server.jar:git-Spigot-549c1fa-70cc382]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [server.jar:git-Spigot-549c1fa-70cc382]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [server.jar:git-Spigot-549c1fa-70cc382]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [server.jar:git-Spigot-549c1fa-70cc382]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: 16
        at java.lang.String.substring(Unknown Source) ~[?:1.8.0_151]
        at me.jul1an_k.tablist.global.api.impl.bukkit.tabprefix.TabPrefix_TeamBased.setupGroup(TabPrefix_TeamBased.java:114) ~[?:?]
        at me.jul1an_k.tablist.bukkit.listener.Join_Listener.onJoin(Join_Listener.java:62) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_151]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_151]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_151]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_151]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[server.jar:git-Spigot-549c1fa-70cc382]

        ... 14 more

CONFIG:
EnableAutoUpdater: true
PluginAutoUpdate: 3600
TabAutoUpdate: 3
TagAutoUpdate: 3
Header:
  text: '&b&lSkyMine &r&lNetWork'
  use: true
Footer:
  text: '&a&lOnline: &r&l%server_online%'
  use: true
HideGM3: false
Join:
  Title:
    text: '&5Welcome to'
    subtext: '&5A Minecraft Server!'
    fadein: 5
    stay: 20
    fadeout: 5
    use: false
  Actionbar:
    text: '&5Have fun!'
    use: false
RandomColors:
- '&0'
- '&1'
- '&2'
- '&3'
- '&4'
- '&5'
- '&6'
- '&7'
- '&8'
- '&9'
- '&a'
- '&b'
- '&c'
- '&d'
- '&e'
- '&f'
UseExternalScoreboard: true
ConfigVersion: 3.0.0-pre1

GROUPS:
Owner:
  Prefix: '&4&lOWNER &D'
  Suffix: ''
Helper:
  Prefix: '&4&lHELPER &D'
  Suffix: ''  
Skygod:
  Prefix: '&b&lSKYGOD &a'
  Suffix: ''
Emperor:
  Prefix: '&1&lEMPEROR &r&1'
  Suffix: ''
Legend:
  Prefix: '&5&lLEGEND &r&5'
  Suffix: ''
Master:
  Prefix: '&3&lMASTER &r&3'
  Suffix: ''
Hero:
  Prefix: '&c&lHERO &r&c'
  Suffix: ''
Twitch:
  Prefix: '&5&lTWITCH &r&5'
  Suffix: ''
default:
  Prefix: '&7'
  Suffix: ''  
  
#Highest Group = Highest group in Tablist
#Lowest Group = Lowsest group in Tablist
GroupSort:
- 'Owner'
- 'Helper'
- 'Skygod'
- 'Emperor'
- 'Legend'
- 'Master'
- 'Hero'
- 'Twitch'
- 'default'

**Comment by DevJul1an** [comment]
Will be fixed in a few hours.

**Comment by DevJul1an** [comment]
Fixed. (https://ci.jumpy91.de/job/sTablist/13/)
