### ISSUE TITLE
[sTablistAPI] Can't find the Class 'net.minecraft.server.v1_12_R1.CraftPlayer'!

### ISSUE THREAD

**Issue by TwanLuttik** [DevJul1an/sTablist#3]
Version: v3.0.0-pre5

i'm using the latest spigot stable version

ERROR:

Error occurred while enabling sTablist v3.0.0-pre5 (Is it up to date?)
java.lang.NullPointerException: null
        at me.jul1an_k.tablist.global.api.impl.bukkit.tablistapi.TablistAPI_NMS.<init>(TablistAPI_NMS.java:46) ~[?:?]
        at me.jul1an_k.tablist.bukkit.sTablistAPI.setupTablistAPI(sTablistAPI.java:49) ~[?:?]
        at me.jul1an_k.tablist.bukkit.Tablist.onEnable(Tablist.java:31) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[server.jar:git-Spigot-549c1fa-70cc382]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [server.jar:git-Spigot-549c1fa-70cc382]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [server.jar:git-Spigot-549c1fa-70cc382]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:382) [server.jar:git-Spigot-549c1fa-70cc382]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:331) [server.jar:git-Spigot-549c1fa-70cc382]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.reload(CraftServer.java:753) [server.jar:git-Spigot-549c1fa-70cc382]
        at org.bukkit.Bukkit.reload(Bukkit.java:525) [server.jar:git-Spigot-549c1fa-70cc382]
        at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:27) [server.jar:git-Spigot-549c1fa-70cc382]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [server.jar:git-Spigot-549c1fa-70cc382]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:649) [server.jar:git-Spigot-549c1fa-70cc382]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchServerCommand(CraftServer.java:635) [server.jar:git-Spigot-549c1fa-70cc382]
        at net.minecraft.server.v1_12_R1.DedicatedServer.aP(DedicatedServer.java:444) [server.jar:git-Spigot-549c1fa-70cc382]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:407) [server.jar:git-Spigot-549c1fa-70cc382]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [server.jar:git-Spigot-549c1fa-70cc382]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [server.jar:git-Spigot-549c1fa-70cc382]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]

-------------------------------------------------------------------------

CONFIG.YML:
![image](https://user-images.githubusercontent.com/19343894/34087665-daf1955e-e3a4-11e7-8f13-a80ae741c622.png)
-------------------------------------------------------------------------
GROUPS.YML:
![image](https://user-images.githubusercontent.com/19343894/34087672-e967c95a-e3a4-11e7-92be-d4241ee5da17.png)

-------------------------------------------------------------------------

**Comment by DevJul1an** [comment]
Will be fixed soon.

**Comment by DevJul1an** [comment]
Fixed. (https://ci.jumpy91.de/job/sTablist/17/)
